"""syka

Revision ID: 3d70e9864449
Revises: 9971c1433ea2
Create Date: 2025-10-11 22:06:32.839388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d70e9864449'
down_revision: Union[str, Sequence[str], None] = '9971c1433ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('eyes_health', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('skin_health', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'skin_health')
    op.drop_column('analyses', 'eyes_health')
    # ### end Alembic commands ###
