"""update_analysis_model

Revision ID: 9971c1433ea2
Revises: d823cfd46469
Create Date: 2025-10-11 18:22:42.618868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9971c1433ea2'
down_revision: Union[str, Sequence[str], None] = 'd823cfd46469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('puffiness', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('dark_circles', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('fatigue', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('acne', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('skin_condition', sa.Text(), nullable=True))
    op.alter_column('analyses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('analyses', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('analyses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('analyses', 'skin_condition')
    op.drop_column('analyses', 'acne')
    op.drop_column('analyses', 'fatigue')
    op.drop_column('analyses', 'dark_circles')
    op.drop_column('analyses', 'puffiness')
    op.drop_column('analyses', 'recommendations')
    # ### end Alembic commands ###
